"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](red)\
$os\
[](fg:red bg:peach )\
$directory\
[](fg:peach bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:yellow)\
$git_branch\
$git_status\
[ ](fg:yellow)\
$cmd_duration\
$line_break\
$character"""

palette = 'matte_black'

[os]
disabled = false
style = "bg:red fg:base"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:base"
style_root = "bg:red fg:base"
format = '[ $user]($style)'

[directory]
style = "bg:peach fg:base"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = ""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:base bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:base bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:base bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:base bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:base bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:base bg:lavender)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.matte_black]
# Based on Matte Black color scheme
red = "#D35F5F"        # Matte Black Red
peach = "#e68e0d"      # Matte Black Orange/Blue variant
yellow = "#FFC107"     # Matte Black Yellow/Green
green = "#FFC107"      # Matte Black Yellow/Green (same as yellow for consistency)
teal = "#bebebe"       # Matte Black Cyan/White
sky = "#bebebe"        # Matte Black light gray
sapphire = "#e68e0d"   # Matte Black Orange/Blue
blue = "#e68e0d"       # Matte Black Orange/Blue
lavender = "#D35F5F"   # Matte Black Magenta/Red
text = "#bebebe"       # Matte Black foreground
subtext1 = "#eaeaea"   # Matte Black bright white
subtext0 = "#8a8a8d"   # Matte Black dim foreground
overlay2 = "#8a8a8d"   # Matte Black bright black
overlay1 = "#333333"   # Matte Black normal black
overlay0 = "#333333"   # Matte Black selection
surface2 = "#333333"   # Matte Black normal black
surface1 = "#121212"   # Matte Black background
surface0 = "#121212"   # Matte Black background
base = "#121212"       # Matte Black base background
mantle = "#121212"     # Matte Black background
crust = "#121212"      # Matte Black background 